name: Deploy IaC using Terraform

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        description: 'Terraform Action'
        default: apply
        type: choice
        options:
          - apply
          - destroy
          - plan
      target_environment:
        description: 'Select target environment'
        required: true
        type: choice
        default: dev
        options:
          - dev
      destroy_resources:
        description: 'Actually destroy resources?'
        type: boolean
        default: false

defaults:
  run:
    shell: bash

run-name: ${{ github.workflow }} - Terraform ${{ inputs.terraform_action }} (${{ inputs.target_environment }}) by @${{ github.actor }}

permissions:
  id-token: write
  contents: read
  pull-requests: write
  security-events: write

jobs:
  call-terraform-deploy:
    name: "Run terraform ${{ inputs.terraform_action }} for ${{ inputs.target_environment }}"
    uses: kewalaka/github-azure-iac-templates/.github/workflows/terraform-deploy-template.yml@main
    with:
      terraform_action: ${{ inputs.terraform_action }}
      environment_name_plan: "${{ inputs.target_environment }}-iac-plan"
      environment_name_apply: "${{ inputs.target_environment }}-iac-apply"
      tfvars_file: "./environments/${{ inputs.target_environment }}.terraform.tfvars"
      destroy_resources: ${{ inputs.destroy_resources == true || inputs.terraform_action == 'destroy' }}
      
      # optional variables 
      # ------------------

      # This block can be removed, set here to illustrate how to use them.
      
      # by default this is false, and can be removed once runners are available, or if you don't want to use resource firewalls.
      # runner_name: "my-ubuntu-runner"
      unlock_resource_firewalls: true 
      
      enable_checkov: false
      enable_static_analysis_checks: false

      # set INFRACOST_API_KEY in repository secrets before enabling
      enable_infracost: false

      root_iac_folder_relative_path: "./iac"

      # for more options check ./github/workflows/terraform-deploy-template.yml
      # -------------------
    secrets: inherit